title: Spectrum Syntax

# Site URLs (Netlify root)
url: "https://spectrumsyntax.netlify.app"
baseurl: ""                     # keep blank on Netlify root

# Build/behaviour
permalink: pretty
timezone: America/Toronto
relative_permalinks: false      # harmless, but unused by Jekyll 4

include:
  - "_pages"

exclude:
  - "_includes/notes_graph.json"

use_html_extension: false
open_external_links_in_new_tab: true
embed_tweets: false

plugins:
  - jekyll-last-modified-at     # ensure it's in your Gemfile

sass:
  sass_dir: _sass
  style: "compressed"

# --- Collections ---
collections:
  notes:
    output: true
    permalink: /:slug
  tumbles:
    output: true
    permalink: /tumbling/:name/

# --- Defaults (layouts, etc.) ---
defaults:
  # Default layout for everything (fallback)
  - scope:
      path: "**/*"
    values:
      layout: "default"

  # Notes get the 'note' layout
  - scope:
      path: "_notes/**/*.md"
    values:
      layout: "note"

  # Tumble collection items use the 'tumble' layout
  - scope:
      path: ""
      type: "tumbles"
    values:
      layout: "tumble"
  
  # Tumbles inside _notes should publish under /tumbling/:basename/
  - scope:
      path: "_notes/_tumbles"
    values:
      layout: "tumble"
      permalink: "/tumbling/:basename/"
      

# (Remove multilingual keys since plugin is disabled)
# languages:
#  - en
#  - pt
#  - fr
# default_lang: en