[build]
  command = "bundle install && bundle exec jekyll build --trace"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.1"
  JEKYLL_ENV = "production"

# (Removed redirect to /admin; public checklist now lives at /tumbling/log-checklist/)
