[build]
  command = "bundle exec rake webp && bundle exec jekyll build --trace"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.1"
  BUNDLER_VERSION = "2.7.1"
  JEKYLL_ENV = "production"
  # Netlify Secrets Scanner: omit non-sensitive username value from scanning
  # to avoid false positives where the username text appears in content/assets.
SECRETS_SCAN_OMIT_KEYS = "ADMIN_USER"

# Redirect Tumbling to Rockhounding section
[[redirects]]
  from = "/tumbling/"
  to = "/rockhounding/tumbling/"
  status = 301

# (Removed redirect to /admin; public checklist now lives at /tumbling/log-checklist/)

# Redirects for reorganized rock category paths
[[redirects]]
  from = "/rockhounding/rocks/category/igneous/"
  to = "/rockhounding/rocks/igneous/"
  status = 301

[[redirects]]
  from = "/rockhounding/rocks/category/metamorphic/"
  to = "/rockhounding/rocks/metamorphic/"
  status = 301

[[redirects]]
  from = "/rockhounding/rocks/category/sedimentary/"
  to = "/rockhounding/rocks/sedimentary/"
  status = 301

# Removed standalone Minerals index; redirect to combined Rocks & Minerals
[[redirects]]
  from = "/rockhounding/rocks/minerals/"
  to = "/rockhounding/rocks/"
  status = 301

# Consolidate logs under Rockhounding
[[redirects]]
  from = "/logs/"
  to = "/rockhounding/logs/"
  status = 301

# Redirects for moved rock pages
[[redirects]]
  from = "/rockhounding/rocks/breccia/"
  to = "/rockhounding/rocks/sedimentary/breccia/"
  status = 301

[[redirects]]
  from = "/rockhounding/rocks/conglomerate/"
  to = "/rockhounding/rocks/sedimentary/conglomerate/"
  status = 301

[[redirects]]
  from = "/rockhounding/rocks/limestone/"
  to = "/rockhounding/rocks/sedimentary/limestone/"
  status = 301

[[redirects]]
  from = "/rockhounding/rocks/gneiss/"
  to = "/rockhounding/rocks/metamorphic/gneiss/"
  status = 301

[[redirects]]
  from = "/rockhounding/rocks/unakite/"
  to = "/rockhounding/rocks/metamorphic/unakite/"
  status = 301

[[redirects]]
  from = "/rockhounding/rocks/granite/"
  to = "/rockhounding/rocks/igneous/granite/"
  status = 301

# Admin auth is enforced via Netlify Edge Function (see [[edge_functions]] below)

[[edge_functions]]
  path = "/admin"
  function = "admin-auth"

[[edge_functions]]
  path = "/admin/*"
  function = "admin-auth"

# Optionally protect the upload function with the same Basic Auth.
# Note: fetch() should reuse cached Basic credentials, but mobile Safari may not.
# If this causes issues when uploading from phone, remove or comment this block
# and rely on ADMIN_SECRET in the function instead.
[[edge_functions]]
  path = "/.netlify/functions/upload-asset"
  function = "admin-auth"

# --- Security headers ---
[[headers]]
  for = "/*"
  [headers.values]
    # Restrictive CSP without unsafe-eval. 'unsafe-inline' kept to support small inline scripts.
    # If/when scripts are moved to external files with nonces, this can be tightened.
    Content-Security-Policy = "default-src 'self'; script-src 'self' https://cdnjs.cloudflare.com 'unsafe-inline'; object-src 'none'; connect-src 'self'; img-src 'self' data: https://upload.wikimedia.org https://static.wikia.nocookie.net; style-src 'self' 'unsafe-inline'; font-src 'self' data:; frame-src 'self'; base-uri 'self'; form-action 'self'"
    Referrer-Policy = "strict-origin-when-cross-origin"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "SAMEORIGIN"
    Permissions-Policy = "geolocation=(), microphone=(), camera=()"
