[build]
  command = "bundle install && bundle exec jekyll build --trace"
  publish = "_site"

[build.environment]
  RUBY_VERSION = "3.2.1"
  JEKYLL_ENV = "production"

# Permanent redirect for legacy checklist URL
[[redirects]]
  from = "/tumbling/log-checklist/"
  to = "/admin/"
  status = 301
  force = true
