name: Asset Sanity

on:
  pull_request:
  push:
    branches: [ main, master ]

jobs:
  zero-byte-check:
    name: Zero-byte images in assets/tumbling
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Find zero-byte files
        id: find_zero
        run: |
          set -euo pipefail
          echo "Scanning for zero-byte files under assets/tumbling..."
          FILES=$(find assets/tumbling -type f -size 0 -print || true)
          if [ -n "${FILES}" ]; then
            echo "Found zero-byte files:" >&2
            echo "${FILES}" >&2
            echo "files<<EOF" >> $GITHUB_OUTPUT
            echo "${FILES}" >> $GITHUB_OUTPUT
            echo "EOF" >> $GITHUB_OUTPUT
            exit 1
          else
            echo "No zero-byte files found."
          fi

  # Optional: warn about missing referenced images in logs (non-fatal)
  referenced-paths-check:
    name: Referenced tumbling images exist (warning)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Grep referenced asset paths
        id: grep_paths
        run: |
          set -euo pipefail
          mkdir -p .tmp
          rg -No "/assets/tumbling/[^"]+" _tumble_logs || true > .tmp/refs.txt
          if [ ! -s .tmp/refs.txt ]; then
            echo "No referenced tumbling assets found in logs."
            exit 0
          fi
          echo "Checking referenced asset paths..."
          MISSING=0
          while IFS= read -r p; do
            rel=${p#/}
            if [ ! -f "$rel" ] || [ ! -s "$rel" ]; then
              echo "WARN: Missing or empty referenced asset: $p" >&2
              MISSING=1
            fi
          done < .tmp/refs.txt
          echo "Done."
          # Do not fail the job; just emit warnings
          exit 0

