name: Release

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate release notes from CHANGELOG
        id: notes
        shell: bash
        run: |
          set -euo pipefail
          TAG_NO_V="${GITHUB_REF_NAME#v}"
          awk -v tag="$TAG_NO_V" '
            BEGIN{p=0}
            /^## \[/{ if (p) exit }
            $0 ~ "^## \\[" tag "\\]" { p=1 }
            p { print }
          ' CHANGELOG.md > RELEASE_NOTES.md || true

          if [ ! -s RELEASE_NOTES.md ]; then
            echo "No changelog section found for $TAG_NO_V; using a placeholder." >&2
            printf "## %s\n\nNo detailed notes. See commits.\n" "$GITHUB_REF_NAME" > RELEASE_NOTES.md
          fi

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: ${{ github.ref_name }}
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false

